export const fontSize = {
  h0: "3em",
  h1: "2.5em",
  h2: "2em",
  h3: "1.5em",
  h4: "1.25em",
  h5: "1em",
  h6: "0.8em",
  caption: "0.875em",
  normal: "1em",
  a_extraSmall: "6px",
  b_tiny: "8px",
  c_smallCaption: "9px",
  d_caption: "10px",
  e_smallSubtitle: "11px",
  f_subtitle: "12px",
  g_smallNormal: "13px",
  h_normal: "14px",
  i_largeNormal: "15px",
  j_title: "16px",
  k_largeTitle: "17px",
  l_highlight: "18px",
  m_subheading: "19px",
  n_heading: "20px",
  o_largeHeading: "22px",
  p_extraLargeHeading: "24px",
  q_smallDisplay: "26px",
  r_display: "28px",
  s_largeDisplay: "32px",
  t_extraLargeDisplay: "36px",
  u_jumboDisplay: "38px",
  v_superDisplay: "40px",
} as const;

export type FontSizeType = typeof fontSize;
